services:
  # API Service (Development)
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/apps/api/node_modules
      - /app/node_modules
    networks:
      - jobswipe-network
    command: pnpm dev

  # Web App (Development)
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3002
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/apps/web/node_modules
      - /app/node_modules
    depends_on:
      - api
    networks:
      - jobswipe-network
    command: pnpm dev

  # Docs App (Development)
  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/docs:/app/apps/docs
      - ./packages:/app/packages
      - /app/apps/docs/node_modules
      - /app/node_modules
    networks:
      - jobswipe-network
    command: pnpm dev


networks:
  jobswipe-network:
    driver: bridge
